FROM public.ecr.aws/lambda/python:3.12

# Copy requirements and install
COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements.txt

# Copy application files
COPY app.py ${LAMBDA_TASK_ROOT}/
COPY static ${LAMBDA_TASK_ROOT}/static/

# AWS Lambda Handler
CMD [ "app.handler" ]
